Repository Callbritton/monster_shop_2005, pull requests merged in 2020-09, with the labels that each got.

#3 User story 2
  app/controllers/home_controller.rb
  app/views/home/index.html.erb
  app/views/layouts/application.html.erb
  app/views/users/new.html.erb
  config/routes.rb
  spec/features/navigation_spec.rb
  spec/features/users/new_spec.rb
Labels: Ready to Merge

#6 User 5
  app/controllers/application_controller.rb
  app/views/layouts/application.html.erb
  spec/features/admin/admin_user_spec.rb
Labels: Ready to Merge, Tests Passing

#7 Story 6-9 error fix
  app/controllers/admin/base_controller.rb
  app/controllers/admin/dashboard_controller.rb
  app/controllers/application_controller.rb
  app/controllers/cart_controller.rb
  app/controllers/merchant/base_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/admin/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  app/views/merchant/dashboard/index.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  spec/features/admin/404_spec.rb
  spec/features/merchants/404_spec.rb
  spec/features/users/404_spec.rb
  spec/features/users/new_spec.rb
  spec/features/visitors/visitor_navigation_spec.rb
Labels: Ready to Merge, Tests Passing

#14 Story 23 24
  app/controllers/cart_controller.rb
  app/models/cart.rb
  app/views/cart/show.html.erb
  config/routes.rb
  spec/features/cart/item_quantity_spec.rb
  spec/features/items/index_spec.rb
  spec/models/cart_spec.rb
Labels: Ready to Merge, Tests Passing

#19 Story 27
  app/views/users/show.html.erb
  spec/features/users/404_spec.rb
  spec/features/users/show_spec.rb
Labels: Ready to Merge, Tests Passing

#21 Story 34 35
  app/controllers/merchant/dashboard_controller.rb
  app/models/merchant.rb
  app/models/order.rb
  app/models/user.rb
  app/views/merchant/dashboard/index.html.erb
  db/migrate/20200913131820_add_merchant_to_users.rb
  db/schema.rb
  spec/features/cart/checkout_spec.rb
  spec/features/items/index_spec.rb
  spec/features/logins/login_spec.rb
  spec/features/merchant/dashboard_spec.rb
  spec/features/orders/creation_spec.rb
  spec/models/order_spec.rb
Labels: Ready to Merge, Tests Passing

#29 Story 36
  app/controllers/merchant/items_controller.rb
  app/views/merchant/dashboard/index.html.erb
  app/views/merchant/items/index.html.erb
  config/routes.rb
  spec/features/merchant/dashboard_spec.rb
  spec/features/users/profile_order_spec.rb
Labels: Tests Passing

#36 Story 42 43
  app/controllers/merchant/items_controller.rb
  app/views/merchant/items/index.html.erb
  config/routes.rb
  spec/features/merchant/items/index_spec.rb
Labels: Ready to Merge, Tests Passing

#51 Refactor and polish
  app/assets/stylesheets/application.css
  app/controllers/admin/dashboard_controller.rb
  app/controllers/admin/merchants_controller.rb
  app/controllers/admin/orders_controller 2.rb
  app/controllers/admin/users_controller 2.rb
  app/controllers/admin/users_controller.rb
  app/controllers/cart_controller.rb
  app/controllers/items_controller.rb
  app/controllers/merchant/base_controller.rb
  app/controllers/merchant/dashboard_controller.rb
  app/controllers/merchant/orders_controller.rb
  app/controllers/merchants_controller.rb
  app/controllers/orders_controller.rb
  app/controllers/users_controller.rb
  app/models/cart.rb
  app/models/item.rb
  app/models/merchant.rb
  app/models/order.rb
  app/views/admin/orders/index.html 2.erb
  app/views/admin/users/index.html 2.erb
  app/views/admin/users/show.html 2.erb
  app/views/items/index.html.erb
  config/routes.rb
  spec/features/admin/user_profile_spec 2.rb
  spec/features/admin/user_profile_spec.rb
  spec/features/cart/checkout_spec.rb
  spec/features/cart/show_spec.rb
  spec/features/items/index_spec.rb
  spec/features/items/merchant_items_index_spec.rb
  spec/features/merchant/items/destroy_spec.rb
  spec/features/merchant/orders/show_spec.rb
  spec/features/merchant/orders/update_spec.rb
  spec/features/merchants/404_spec.rb
  spec/features/merchants/destroy_spec.rb
  spec/features/merchants/merchant_navigation_spec.rb
  spec/features/merchants/new_spec.rb
  spec/features/merchants/show_spec.rb
  spec/features/merchants/statistics_spec.rb
  spec/features/navigation_spec.rb
  spec/features/orders/creation_spec.rb
  spec/features/orders/destroy_spec.rb
  spec/features/reviews/destroy_spec.rb
  spec/features/reviews/edit_spec.rb
  spec/features/users/404_spec.rb
  spec/features/users/edit_spec.rb
  spec/features/users/new_spec.rb
  spec/features/users/profile_order_spec.rb
  spec/features/users/show_spec.rb
  spec/models/item_orders_spec.rb
  spec/models/item_spec.rb
  spec/models/merchant_spec.rb
  spec/models/order_spec.rb
  spec/models/review_spec.rb
  spec/models/user_spec.rb
Labels: Ready to Merge, Tests Passing
